--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Bumbumkill/CommandDisabler
build-by-default: true
branches:
- master
projects:
  CommandDisabler:
    path: ""
    icon: "icon.png"
...
